name: appimagetool

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./fetch-gh-release.sh appimagetool AppImage/AppImageKit >>$GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: env.GHR_EXISTS == '0'
        run: |
          ./download-gh-release.sh 'appimagetool-(x86_64|aarch64).AppImage' <"$GHR_RELEASE_FILE"
          ./package-deb-singlebin.sh appimagetool "$GHR_VERSION" appimagetool 'appimagetool-*.AppImage' <<EOF
          Maintainer: nta88
          Section: admin
          Priority: optional
          Description: appimagetool is a tool to package desktop applications as
           AppImages.
          EOF
      - if: env.GHR_EXISTS == '0'
        run: git tag -f "$GHR_TAG_NAME" && git push -f origin "$GHR_TAG_NAME"
      - if: env.GHR_EXISTS == '0'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.GHR_TAG_NAME }}
          artifacts: '*.deb'
          removeArtifacts: true
          artifactErrorsFailBuild: true
          allowUpdates: false
