name: cidr-merger

on:
  workflow_dispatch: {}
  schedule:
    - cron: '16 9 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./fetch-gh-release.sh cidr-merger zhanhb/cidr-merger >>$GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: env.GHR_EXISTS == '0'
        run: |
          ./download-gh-release.sh 'cidr-merger-linux-(amd64|arm64)' <"$GHR_RELEASE_FILE"
          ./package-deb-singlebin.sh cidr-merger "$GHR_VERSION" cidr-merger 'cidr-merger-linux-*' <<EOF
          Maintainer: nta88
          Section: admin
          Priority: optional
          Description: cidr-merger is a simple command line tool to merge ip/ip cidr/ip
            range.
          EOF
      - if: env.GHR_EXISTS == '0'
        run: git tag -f "$GHR_TAG_NAME" && git push -f origin "$GHR_TAG_NAME"
      - if: env.GHR_EXISTS == '0'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.GHR_TAG_NAME }}
          artifacts: '*.deb'
          removeArtifacts: true
          artifactErrorsFailBuild: true
          allowUpdates: false
