name: docker-credential-secretservice

on:
  workflow_dispatch: {}
  schedule:
    - cron: '50 10 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./fetch-gh-release.sh docker-credential-secretservice docker/docker-credential-helpers >>$GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: env.GHR_EXISTS == '0'
        run: |
          ./download-gh-release.sh 'docker-credential-secretservice-.+\.linux-(amd64|arm64)' <"$GHR_RELEASE_FILE"
          ./package-deb-singlebin.sh docker-credential-secretservice "$GHR_VERSION" docker-credential-secretservice 'docker-credential-secretservice-*' <<EOF
          Maintainer: nta88
          Depends: libsecret-1-0
          Section: admin
          Priority: optional
          Description: docker-credential-secretservice is a credential helper backend
           which uses libsecret to keep Docker credentials safe.
          EOF
      - if: env.GHR_EXISTS == '0'
        run: git tag -f "$GHR_TAG_NAME" && git push -f origin "$GHR_TAG_NAME"
      - if: env.GHR_EXISTS == '0'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.GHR_TAG_NAME }}
          artifacts: '*.deb'
          removeArtifacts: true
          artifactErrorsFailBuild: true
          allowUpdates: false
