name: flowy

on:
  workflow_dispatch: {}
  schedule:
    - cron: '26 15 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./fetch-gh-release.sh flowy nathan818fr/flowy >>$GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: env.GHR_EXISTS == '0'
        run: |
          ./download-gh-release.sh 'flowy-linux-(amd64|arm64)' <"$GHR_RELEASE_FILE"
          ./package-deb-singlebin.sh flowy "$GHR_VERSION" flowy 'flowy-linux-*' <<EOF
          Maintainer: nta88
          Section: utils
          Priority: optional
          Description: flowy is a dynamic wallpaper changer.
          EOF
      - if: env.GHR_EXISTS == '0'
        run: git tag -f "$GHR_TAG_NAME" && git push -f origin "$GHR_TAG_NAME"
      - if: env.GHR_EXISTS == '0'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.GHR_TAG_NAME }}
          artifacts: '*.deb'
          removeArtifacts: true
          artifactErrorsFailBuild: true
          allowUpdates: false
